### ISSUE TITLE
Score system broken

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#3]
Round number sometimes go -1

Assassin's won 3 times before, but guards have the points:

![s](https://user-images.githubusercontent.com/47571719/114206129-90267080-994a-11eb-8ef9-f14f9a22cee1.png)

And now, one more win by assassin (as shown in the previous screenshot killcam):

![1](https://user-images.githubusercontent.com/47571719/114206292-b64c1080-994a-11eb-94a5-3622b13297bb.png)

I think the issue comes from when the scores are counted. Since we're 2 players with bots we're moved to guards/bots are kicked when the round start, and it messes up the count

**Comment by TheFrenchGhosty** [comment]
Viking answer:

>to be honest i never figured out why this is happening

>Score fix sent to [ME]

**Comment by VikingKampfsau** [comment]
Finally found the problem.

The issue was that in stock cod4 the teams keep their score, even when they switch sides.
Like in s&d or Sabotage you have been defender and become attacker, but you take your score to the new team. 

However, in ktk you switch sides but not the team.
Means the score remains in the team that achieved it.

The old Code checked the score of the guards on every new round and subtracted this value from the amount of already played rounds to get the score of the assassin. 
Tbh i have no idea why this failed from time to the time.

What i do now is to assign the score of the assassins to the guards (and opposite) when the teams switch sides.
After that the game continues to count the score itself.

**Comment by TheFrenchGhosty** [comment]
Fixed.
